/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dad21_finalProject_student_database;

import io.javalin.Javalin;

public class App {

    public final static int PORT = 4567;

    public static void main(String[] args) {
        var app = Javalin.create(config -> {
            config.addStaticFiles("public");
        }).start(PORT);

        app.get("/", AppServe::root);
        app.get("/md", AppServe::md);
    }

}
