/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package studentDatabase;

import org.junit.Test;

import studentDatabase.Pojo.Account;
import studentDatabase.Pojo.Course;

public class AppTest {
    
    @Test public void testHibernate(){
        var c = new Course("ISE", "101", "Introduction to engineering", "nothing given");
        var ac = new Account("15d","TaiMan","Chan","ISE","M","+852-21090000");
        App.testDB(c);
        App.testDB(ac);
    }
}
