/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package studentDatabase;

import io.javalin.Javalin;
import studentDatabase.Pojo.Account;
import studentDatabase.Pojo.Course;
import studentDatabase.Pojo.Dept;

public class App {
    
    public final static int PORT = 4567;
    
    public static void main(String[] args) {
        var app = Javalin.create(config -> {
            config.addStaticFiles("public");
        }).start(PORT);
        
        app.get("/", AppServe::root);
        app.get("/md", AppServe::md);
        
    }
    

    
}
