/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package studentDatabase;

import io.javalin.Javalin;
import studentDatabase.Pojo.Account;
import studentDatabase.Pojo.Course;

public class App {

    public final static int PORT = 4567;

    public static void main(String[] args) {
        var app = Javalin.create(config -> {
            config.addStaticFiles("public");
        }).start(PORT);

        app.get("/", AppServe::root);
        app.get("/md", AppServe::md);
        

    }
    public static void testDB(Account a) {
        var db = new DBUtil();
        var sql2o = db.getSql2o();
        var sql = "insert into Account(netid,firstname,lastname,deptid,gender,phone)" +
        " values (:netid, :firstname, :lastname, :deptid, :gender, :phone)";
        
        try(var con = sql2o.beginTransaction()){
            con.createQuery(sql)
            .bind(a)
            .executeUpdate();
        }
        
    }
    
    public static void testDB(Course c) {
        var db = new DBUtil();
        var sql2o = db.getSql2o();
        var sql = "insert into Course(deptid,courseid   ,coursename,remarks )" +
        " values (:deptid, :courseid , :coursename, :remarks )";
        
        try(var con = sql2o.beginTransaction()){
            con.createQuery(sql)
            .bind(c)
            .executeUpdate();
        }
        
    }

}
