/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dad21_finalProject_student_database;

import org.junit.Test;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        // assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
